# server
server:
  port: 2023
  
spring:
# 콘솔 색상
  output:
    ansi:
      enabled: always

# DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/watchdog
    username: root
    password: test123

# query
  jpa:
    open-in-view: false #spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
    show-sql: true # true 설정시 JPA 쿼리문 확인 가능
    hibernate: 
      ddl-auto: none # DDL(create, alter, drop, none) 정의시 DB의 고유 기능을 사용할 수 있다.

# JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여준다.
# spring.jpa.properties.hibernate.format_sql=true

# View
  # mvc:
  # view:
  #  prefix: /WEB-INF/views/
  #  suffix: .jsp

#JSP와 같이 사용할 경우 뷰 구분을 위해 컨트롤러가 뷰 이름을 반환할때 thymeleaf/ 로 시작하면 타임리프로 처리하도록 view-names 지정
  mvc:
    view:
  # thymeleaf:
      prefix: classpath:templates/
      suffix: .html
# thymeleaf를 사용하다 수정 사항이 생길 때 수정을 하면 재시작을 해줘야 한다. 이를 무시하고 브라우저 새로고침시 수정사항 반영을 취해 cache=false 설정(운영시는 true)
  thymeleaf:
      cache: false
      check-template-location: true
      
# 디버그
logging:
  level:
    "[kr.or.kimsn.radar]": DEBUG
